#配置日志级别
#logging:
#  level:
#   root: trace

##  配置日志文件的文件名
#logging:
#  file:
#    name: logger/spring.log

##配置日志文件的存储目录:
logging:
  file:
    path: D:/logger
#对日志文件进行分割
#logging:
  logback:
    rollingpolicy:
      max-file-size: 1KB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
